import { existsSync, mkdirSync, renameSync, unlinkSync } from "fs";
import { resolve } from "path";
import { getDb } from "../parser/db.js";
import { queryApprovedMemoriesForProject } from "../parser/queries.js";

export async function syncMemoriesToFile(projectId: string): Promise<void> {
	const db = getDb();

	// Look up project path
	const projRow = db
		.prepare("SELECT path FROM projects WHERE encoded_name = ?")
		.get(projectId) as { path: string } | null;
	if (!projRow) return; // No project path — skip silently

	const projectPath = projRow.path;
	const claudeDir = resolve(projectPath, ".claude/memory");
	const memoryFile = resolve(claudeDir, "MEMORY.md");
	const tempFile = resolve(claudeDir, ".MEMORY.md.tmp");

	// Query approved memories
	const memories = queryApprovedMemoriesForProject(db, projectId);

	if (memories.length === 0) {
		// No approved memories — remove file if it exists
		try {
			if (existsSync(memoryFile)) unlinkSync(memoryFile);
		} catch {
			// Ignore removal errors
		}
		return;
	}

	// Group by category (use first category for multi-tag memories)
	const grouped = new Map<string, string[]>();
	for (const mem of memories) {
		const primaryCat = mem.category.split(",")[0].trim();
		const cat = primaryCat.charAt(0).toUpperCase() + primaryCat.slice(1);
		if (!grouped.has(cat)) grouped.set(cat, []);
		grouped.get(cat)!.push(mem.content);
	}

	// Format as markdown
	const lines: string[] = [
		"# Project Memories",
		"",
		"> Auto-generated by CodeForge dashboard. Do not edit manually.",
		"",
	];

	for (const [category, items] of grouped) {
		lines.push(`## ${category}`);
		for (const item of items) {
			lines.push(`- ${item}`);
		}
		lines.push("");
	}

	const content = lines.join("\n");

	// Write atomically: temp file then rename
	mkdirSync(claudeDir, { recursive: true });
	await Bun.write(tempFile, content);
	renameSync(tempFile, memoryFile);
}
