name: "Publish DevContainer Features"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['container/.devcontainer/features/**']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./container/.devcontainer/features"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
